### ISSUE TITLE
Add field for US VIN

### ISSUE THREAD

**Issue by cool-RR** [django/django-localflavor#153]
17 characters, without I, O and Q, capitalize automatically including lookups.

**Comment by benkonrath** [comment]
I assume you're referring to the international VIN standard:
https://en.wikipedia.org/wiki/Vehicle_identification_number

A VIN field definitely fits in the generic module of this project. It could accept a list of countries to validate against so that counties can be excluded or included as required (just like the IBAN field).

This project relies heavily on code contributions from our users. The collaborators mostly review these contributions and help out with bug fixes as problems come up. This feature fits into django-localflavor and we would happily accept a pull request that implements a VIN field. I'm closing this issue just a matter of housekeeping.

**Comment by cool-RR** [comment]
Why close the issue? If it's a valid feature request why not leave it open
indefinitely until someone implements? If it's cluttering the bug reports
maybe use tagging?

**Comment by benkonrath** [comment]
I closed this issue because it's been sitting open with no comments for more than half a year and it's highly unlikely that one of the maintainers will implement it. Closing the issue makes it clear that nobody is working on it, provides focus for the maintainers and gives clear feedback to the person who reported it.

As I said in the previous comment, the feature fits into localflavor but a PR is the way forward. There are some exceptions but the maintainers mostly review PRs and work on the project infrastructure. In other words, users mostly write the code and implement the features.

Of course this is just my opinion. The other collaborators / maintainers can disagree and reopen it.
