### ISSUE TITLE
Mexico RFC invalid

### ISSUE THREAD

**Issue by Woile** [django/django-localflavor#204]
The [RFC](https://github.com/django/django-localflavor/blob/master/localflavor/mx/forms.py#L73) regex is not right, I've used the one mentioned in [this](http://regexlib.com/REDetails.aspx?regexp_id=1065&AspxAutoDetectCookieSupport=1) web and seems to work fine.

```
r'^([A-Z|a-z|&amp;]{3}\d{2}((0[1-9]|1[012])(0[1-9]|1\d|2[0-8])|(0[13456789]|1[012])(29|30)|(0[13578]|1[02])31)|([02468][048]|[13579][26])0229)(\w{2})([A|a|0-9]{1})$|^([A-Z|a-z]{4}\d{2}((0[1-9]|1[012])(0[1-9]|1\d|2[0-8])|(0[13456789]|1[012])(29|30)|(0[13578]|1[02])31)|([02468][048]|[13579][26])0229)((\w{2})([A|a|0-9]{1})){0,3}$'
```

With the current regex, this RFC `GOH831115` is valid and in [this web](https://portalsat.plataforma.sat.gob.mx/ConsultaRFC/) says it is not valid.

If you want I can make a PR, np.

Thank you

**Comment by benkonrath** [comment]
Thanks for the bug report. It looks like the min length should be 12 instead of 9. 

https://technet.microsoft.com/en-us/library/hh242611.aspx

This means that the regex is also wrong because the last part isn't optional. I don't want to copy the regext from that website because I don't know what the license is. I'll fix this.

**Comment by Woile** [comment]
Wow I didn't know regex could be licensed :/ 
Thanks for the update, I will be uploading my project soon.
