### ISSUE TITLE
Proposal: move repo to jazzband organisation

### ISSUE THREAD

**Issue by jscn** [django/django-localflavor#205]
There are a number of open pull requests which have been hanging around for some time, awaiting merge or review. It seems as though the repository owners no longer have the time to follow them all up.

Is it worth moving the project to the [jazzband](https://github.com/jazzband) organisation in order to spread the load a bit?

Please do close this issue if this isn't the right forum for this discussion.

**Comment by nagisa** [comment]
I do not perceive the so-called load at all here. Due to the nature of the project, no single person is at all qualified to review changes to all the localflavours. For example, I maintain the localflavours of baltic countries, and I feel confident enough merging changes to them, but I have a hard time even imagining the work involved in reviewing localflavour of some South American country – and the documentation is more often than not isn’t available in English.

I believe that to be *the* primary reason why there’s 12 pull requests currently open and I do not see how moving repository would help solving the problem described in any way.

**Comment by benkonrath** [comment]
Moving this project to jazzband is something I've considered proposing as well but in the end, I also thought that wouldn't help getting the PRs reviewed and merged faster. As nagisa pointed, we mostly rely on people with local knowledge contribute new fields and bug fixes and not every collaborator can review all of the PRs. I personally try to review PRs with documentation in languages that I don't speak, but it does take extra time. We're also still catching up on the PR reviews that were started by people who've taken a step back from this project recently which again takes extra time.

That's not say that we can't improve things - the fact that you're proposing this change is a good indication that there's a problem here. We should probably document who's responsible for or has expertise in a given area so people know who to ping when the response is taking too long.  @nagisa @claudep Do you have any thoughts on this? I'm not sure what would be the best place for this: the README, a wiki page or something else.

I've also been pushing off working on this project for the last little while because I'm planning to spend the DjangoCon EU sprint (this coming weekend) working on this project. I should have communicated this better and I'll take this as a point to improve for the next sprint where I plan to work on django-localflavor.

**Comment by claudep** [comment]
I don't think that the maintainership of this module is in such a bad state. I think that pull requests of good quality with tests and documentation generally do not take too long to be committed. Feel free to point at specific issues.

**Comment by nagisa** [comment]
> We should probably document who's responsible for or has expertise in a given area so people know who to ping when the response is taking too long. @nagisa @claudep Do you have any thoughts on this? I'm not sure what would be the best place for this: the README, a wiki page or something else.

@benkonrath in rust-lang we use a bot called [highfive](https://github.com/nrc/highfive) which automatically assigns every PR to some maintainer based on the [directory the PR is aimed at](https://github.com/nrc/highfive/blob/master/highfive/configs/rust.json#L8). Since all localflavours have their own directory, I think something like that could work well.

(also see https://www.youtube.com/watch?v=dIageYT0Vgg)

**Comment by benkonrath** [comment]
@nagisa highfive looks great. It will give us a nice overview of who's involved with which localflavor. After watching the video and looking at the sources, It's not clear to me how it's configured for a specific repo? Do you know how to do it?

**Comment by nagisa** [comment]
@benkonrath One can run their own instance, the [README](https://github.com/nrc/highfive/blob/master/README.md#adding-a-project) contains the setup instructions. 

That being said, there’s [a bunch of code](https://github.com/nrc/highfive/blob/master/highfive/newpr.py#L188) hardcoded for assumptions about rust-lang repos, so it is very likely bot will need adaptations (or it might be easier to write localflavour’s own) to not be hardcoded for rust-lang repos.

**Comment by jieter** [comment]
@claudep Since you are asking for specific numbers: #152 was first proposed on 2015-05-09 (incomplete), almost complete at 2015-09-10, merged on 2015-12-02 and still not released to pypi today.

Time between releases seems to be quite long too:
1.2 released on 2015-11-27
1.1 released on 2014-12-10
1.0 released on 2013-07-29

While I can and do understand the reasons for these delays, for me, they're not acceptable: I do not open PR's for code I do not use, but for code I need for actual projects. As a workaround, I use the url to the zip download of the branch for the PR on github in my requirements.txt, which is not really robust of course.
Can we release more often to get this changes shippped?

**Comment by claudep** [comment]
@jieter thanks for these numbers. The fact that we enrolled Ben in the releasers team was also in the hope that we could release more often. Talking of that, Ben, what about releasing 1.3 soon to prove that :-)

**Comment by benkonrath** [comment]
@nagisa Thanks for the info on highfive. I was hoping for something more plug and play but even if it was, it seems this should be setup for the django project as a whole rather than just localflavor. Unfortunately I don't have the time to drive something like this forward right now.

@claudep  Yeah, I can cut a release soon. I was hoping to get the deprecation stuff in place before the next release but I'll just leave that until the following release. I've setup the 1.3 milestone for the issues that I want to get done before 1.3: 
https://github.com/django/django-localflavor/milestones/1.3

Feel free to adjust the milestone as you see fit. I'll be working on this in bits and pieces this week.

**Comment by jscn** [comment]
> We should probably document who's responsible for or has expertise in a given area so people know who to ping when the response is taking too long.

It might be good to document what "too long" is for this project. Should contributors expect a turnaround of a few days or a few weeks or ..?

**Comment by benkonrath** [comment]
@jscn You'll have to use your best judgement on when to remind people. I'm reluctant to provide exact response timelines because I can't speak for the other contributors and I don't want people to get unrealistic expectations.

I'm going to close this issue as the active contributors have agreed that contributing this project to jazzband isn't the right move for us right now.

**Comment by jieter** [comment]
Releasing more often, with smaller change logs might not require more developer/maintainer time and will fix my problem of waiting long before a new release is made. Any reason not to release once a PR is properly reviewed and merged?

It shouldn't be hard to automate it enough to make it a quick task...

**Comment by claudep** [comment]
Releasing more often is definitely desirable. After each PR doesn't seem realistic. You can always install from Github if you really need a new feature immediately.

**Comment by benkonrath** [comment]
@jieter It's coming: #228 I just ran out of time before I head offline for a week (starting tomorrow).
