### ISSUE TITLE
Change 'DIF' to 'CDMX' in mx_states.py

### ISSUE THREAD

**Issue by svmalvaez** [django/django-localflavor#234]
in STATE_CHOICES change

('DIF', _('Distrito Federal')),

to

('CDMX', _('Ciudad de México')),

**Comment by orf** [comment]
This is a tricky one, because we have to make the change in a backward compatible way. I propose that we do this in two stages, firstly we rename 'Distrito Federal' to 'Ciudad de México' and keep the 'DIF' key. We also add a deprecation warning to the Mexican models/forms that throws when 'DIF' is encountered.

The end-user needs to run a migration to migrate 'DIF' to 'CDMX', and once they do they can add a setting that stops the warning, and causes the key to be 'CDMX'.

**Comment by orf** [comment]
I took a stab at this at the recent DUTH conference sprints and made good headway, which can be found in #256. The problem is pretty tricky and I wanted to document the solution we came up with in this ticket, although it's not specific to this issue.

Simply renaming `DIF` to `CDMX` will cause issues with people who have `DIF` in their database as the choice is suddenly not there. Things like `get_X_display` won't work and any select boxes will not show the correct value. We could change the display name to be `Ciudad de México` and leave the key as `DIF`, but then the value is technically wrong.

So, users of the library who use the `mx_states` fields need to update their code to support `CDMX` over `DIF`, this is unavoidable. But we want this to be as seamless as possible, ideally `localflavor` would bundle a migration that would take care of this for the user when they ran `manage.py migrate`.

However because `localflavor` bundles fields rather than models this is not possible. There is no way for us to tie into the existing migrations infrastructure, which is unfortunate but not the end of the world. So, we need to ship a management command that users of the library can run to do the migrations for themselves. [I've implement this here.](https://github.com/orf/django-localflavor/blob/2f6c48c113db93a567af912832fc51a01c5892e2/localflavor/management/commands/run_localflavor_datamigrations.py#L37). This is a general command that can be extended in the future with any new renames that we need.

Alongside this [I implemented a check in the clean method to replace instances of DIF to CDMX](https://github.com/django/django-localflavor/pull/256/commits/7f18570d07745dbe348dfc3d346ddfdb6bde8753), so existing database values will be converted silently and the correct choices will be displayed.

This is a general problem with no easy solution. Even with our management command we need to communicate clearly to users that they need to:

   - Run the bloody command
   - Update all references to `DIF` in their code to `CDMX`.
   - In this instance run `makemigrations` to pick up the new 4 length character field.

How and where we do this is something I'm not sure about. We could add a warning in the field itself when it converts a value, but people might not be looking. We could add a warning in the `setup.py`, but then it would only be in English and would only appear when they are installing (and will easily be lost).

We could somehow tie in with the Django checks framework, but I have no idea how. I was explicitly warned *against* running any database queries from within a check.

I think the best way would be to just try and enforce that all users should run `manage.py run_localflavor_datamigrations` every time they upgrade regardless of if they need to or not.

**Comment by benkonrath** [comment]
Thanks for the summary and for your work on this. Since the DUTH sprints, I've also been looking around at options for this and it turns out that localflavor has a solution using the Python Warning control system. 

https://django-localflavor.readthedocs.io/en/latest/#backwards-compatibility

I'm pretty sure this was setup before the checks system was introduced in Django and I don't think it's ever been used this combined version of localflavor. Now that the system check framework is available, I think it's a better solution for this problem because it's built into Django and there's an easy way to disable the warnings.

https://docs.djangoproject.com/en/1.10/ref/checks/

I don't think we should try to get all localflavor users to run the management command after every release. This should be targeted at people who are directly by the fields that need to be migrated.

Here's how I think it should work:

* Add a system check `Warning` to `MXStateField` that explains what needs to be done.
  * As you've already said, tasks for users would as follows: Audit code for usage of DIF, Create and run a migration for the field length change, Run the management command on production data,
  * You don't need to add a test for the old data in the system check. Just raise the `Warning` without any checks. The user will need to silence the `Warning` manually once they've made the required changes.
  * `hint` and `msg` are short fields so we might need host the instructions in the docs and provide a link. Generic instructions might be good enough but I'm not sure.
  * It would be nice if we don't conflict with the Django warning numbers for fields but I'm not sure if there's a convention we can rely on for this.
  * The changelog should clearly indicate that the user needs to take action. Perhaps a new section for this at the top of the changelog would be best but I'm open to suggestions.

* Add add an override in the `clean` method to catch the old data (as you have already done)
  * This should also raise the same warning. If the data is being changed, the user should be notified.

I would also want to have a timeline for removing this migration code in the management command and the data change in `clean`. I suppose we could specify in the warning that the migration code and the data change will be removed in the next major version (in this case 2.0).

I'm curious to hear your thoughts on this. Thanks again.

**Comment by benkonrath** [comment]
Just a quick update on this. The Python warnings system might be the better approach for the notifications. I'm still trying to understand when and when not to use system checks. Ive started a discussion about this on #262. I may post a message to django-devel to get more input.

**Comment by benkonrath** [comment]
It seems that we could use system checks for this but Python warnings is more the approach that Django itself would use. My preferred procedure for this kind of data change stands (comment from yesterday) except that we should use Python warnings instead of system checks. This allows the existing procedure to be used which should simplify things a little. @orf Does this seem like a good way forward to you?

**Comment by orf** [comment]
Hey @benkonrath, sorry for the late reply, I've been a bit busy recently. That approach sounds great, I can find some time this coming weekend to try and implement the warnings in the clean method.
