### ISSUE TITLE
IBANFormField raise django.core.exceptions.ImproperlyConfigured to include_countries=ISO_3166_1_ALPHA2_COUNTRY_CODES

### ISSUE THREAD

**Issue by hugoantunes** [django/django-localflavor#241]
Hello,

I didn't found any issue about this so I hope you can help me.

When a tried to use ISO_3166_1_ALPHA2_COUNTRY_CODES at IBANFormField this exception was raised 
```
django.core.exceptions.ImproperlyConfigured: Explicitly requested country code AF is not part of the configured IBAN validation set.
```

```
from django.forms import ModelForm
from localflavor.generic.forms import IBANFormField
from localflavor.generic.countries.iso_3166 import ISO_3166_1_ALPHA2_COUNTRY_CODES
from bank_user.models import User


class UserForm(ModelForm):
    iban = IBANFormField(include_countries=ISO_3166_1_ALPHA2_COUNTRY_CODES)

    class Meta:
        model = User
        fields = "__all__"
```

From what I could see in 'localflavor/generic/validators.py' line 144 you validate the length of IBAN according to the country initials.  However, there is more countries in ISO_3166_1_ALPHA2_COUNTRY_CODES than IBAN_COUNTRY_CODE_LENGTH.

Do you have any suggestion about how I could proceed ? 
cBest,

**Comment by benkonrath** [comment]
The IBAN format is not defined for all countries.
https://en.wikipedia.org/wiki/International_Bank_Account_Number#Adoption

This means you can't set `include_countries` to `ISO_3166_1_ALPHA2_COUNTRY_CODES` because it's a list of all country codes.

To accept all IBANs in your form, just use the `IBANFormField` with no options like this:

```
class UserForm(ModelForm):
    iban = IBANFormField()
```

Does this help with your problem?

**Comment by hugoantunes** [comment]
@benkonrath your are rigth !!

works perfectly, thank you!

best
