### ISSUE TITLE
docs no longer updated on readthedocs.io

### ISSUE THREAD

**Issue by benkonrath** [django/django-localflavor#393]
The latest version is 2.1:
https://django-localflavor.readthedocs.io/en/latest/

The builds seem to have stopped and the version numbers are not correct.
https://readthedocs.org/projects/django-localflavor/builds/
https://readthedocs.org/projects/django-localflavor/versions/

**Comment by benkonrath** [comment]
@jezdez Any chance you can look into this? Or give claudep or me access? Thanks.

**Comment by jezdez** [comment]
I missed this ticket, apologies, I’ve added you on Readthedocs as a maintainer (feel free to add more people from the Django team) since I don’t have permissions anymore for the repo I can’t add the now required "GitHub incoming webhook integration" on https://readthedocs.org/dashboard/django-localflavor/integrations/create/

You should be able to add it since you have admin permissions for the repo (I hope), Readthedocs will tell you if you don’t. And if not I would suggest to reach out to the Django Ops team or Django fellows to rectify this (cc @apollo13, @MarkusH, @carltongibson, @felixxm).

**Comment by benkonrath** [comment]
Thanks Jannis. I also can't add it. Can any of the Django Ops team or Django fellows help out here? Thanks.

**Comment by MarkusH** [comment]
I can't add it either. Sorry.

**Comment by jezdez** [comment]
> Can someone add me as admin on readthedocs, then I can try.

Done.

**Comment by apollo13** [comment]
Thanks, webhook is created and initial delivery looks good. The next tag/branch should build automatically

**Comment by benkonrath** [comment]
It's working. Thanks everyone for the help!
