### ISSUE TITLE
Transifex strings not in sync with source code

### ISSUE THREAD

**Issue by washeck** [django/django-localflavor#410]
I'm trying to localize BICField validation messages in Transifex and I found out that only "BIC codes have either 8 or 11 characters." is present there. The same source file contains other messages (see https://github.com/django/django-localflavor/blob/master/localflavor/generic/validators.py#L235) but those are absent in Transifex.

**Comment by claudep** [comment]
Looks like it could be a Transifex bug. The update URL pointing to the en source file was marked "Not found". Just giving again the same URL may have fixed this. Let's wait some hours to see what's happening. Thanks for noticing!

**Comment by claudep** [comment]
Seems to be fixed now, thanks again!

**Comment by benkonrath** [comment]
Do we need to do a 3.0.1 release to fix this? I just updated the base catalogue and there were some changes. I'm not sure why they weren't picked up last time. I used the `make-translations` invoke task this time instead of doing it manually.

In any  case, if an update to the 3.0 release would be useful, we can hold off string changes for a week or two to give translators a chance to update things before we pull in the updates and do the release.

**Comment by claudep** [comment]
> I'm not sure why they weren't picked up last time

That was a Transifex bug, not your fault. Sometimes it memorizes that a resource is down and never tries again :-(

Would be a good idea to notify the django-i18n ML and give two weeks for translators before releasing 3.0.1.
